### PR TITLE
Add a function to do in-memory conversion

### PR DESCRIPTION
**Pull request by linkmauve**
This PR is best viewed commit per commit.

The goal is to make vtracer more usable as a library, in order to do so I have moved out path handling and clap parsing from the `Config` struct.  This makes it much better than going through a PNG file, especially when the application already has pixels in memory.

A future commit can make clap and image optional for building the library (in the latter case the `convert_image_to_svg()` function won’t be available).

This is a public API change, because `convert_image_to_svg()` now takes the input and output paths as arguments, whereas before they were passed in the `Config` struct, so a minor version bump will have to follow for the next release.

### CODE REVIEW

**Comment by tyt2y3** [comment]
As per the other issue, do you think it's also needed to add `dylib` to Cargo.toml?

**Comment by linkmauve** [comment]
I’m not sure the right one should be `dylib` either, most Rust projects want to statically link their libraries instead of having to carry a .so around.  For Python it’s the opposite, you do need a .so.  A good solution would be to split this crate, into a library crate, a cli tool crate, a python binding crate, so the user could install whichever they need. This would also have the benefit of letting the library remove its dependency on clap, which isn’t needed for anything but the cli version.

**Comment by tyt2y3** [comment]
Looking at the docs https://doc.rust-lang.org/beta/reference/linkage.html again I think adding `rlib` is the correct option.

**Comment by linkmauve** [comment]
Thanks for the `rlib` fix, this indeed makes this library usable as a Rust library again!

I’ve pushed a new version, rebased on top of master, with the Python binding fixed to use the new API.

**Comment by tyt2y3** [comment]
Thank you for the update. Allow me a bit of time to go through this )

**Review by tyt2y3 — COMMENTED** [review]
I think it looks pretty good. Only blocked by me to actually try this out.

**Review by tyt2y3 — COMMENTED** [review]
Thank you

**Pull request merged**
