### PR TITLE
Python Binding

### PR DESCRIPTION
**Pull request by tyt2y3**
cont'd #52

### CODE REVIEW

**Comment by tyt2y3** [comment]
@etjones Hopefully I did not break things?

How's the CI supposed to work?

**Comment by etjones** [comment]
I'm working on figuring out how the CI works. Maturin has nice cross-compiling machinery, but A) it'll need a little extra configuration to work with the workspace-based top-level Cargo.toml, and B) I'm not sure how the package publishing system works, but I imagine that may be from GH. More news when that's all in hand. 

Thanks for taking a look at all this; it's the first time I've touched any real Rust code and I'm sure there are things I'm missing.

**Comment by etjones** [comment]
OK, I've got all the cross-platform builds (even Windows!) working on my branch. Looks like there's one more tweak I need to make to the `CI.yml` file to get the PyPI release working, but it's close.

Workflow to release is just to commit a tag ( e.g. `v0.6.4`)to the main branch. That would kick off the cross-platform build processes and then do a release to PyPI. 

Still needed: To publish to PyPI, the main VTracer repo will need a secret added called `secrets.PYPI_API_TOKEN` that's associated with the account of a maintainer of the [PyPI Vtracer package](https://pypi.org/project/vtracer/). 

@tyt2y3, I'd be happy to add/transfer ownership of the PyPI project to you so that everything stays with your account. Do you have a PyPI account I could invite to be a maintainer?

**Comment by etjones** [comment]
Aaand, I was going to ask if I should put things in a separate python.rs file and de-clutter converter.rs, but I see you already did! Excellent; that's a better design than my first pass.

**Comment by tyt2y3** [comment]
> I'd be happy to add/transfer ownership of the PyPI project to you so that everything stays with your account. Do you have a PyPI account I could invite to be a maintainer?

Sure. Can you DM me on Discord? `chris.2y3`

**Comment by etjones** [comment]
Just sent an invite.

**Comment by tyt2y3** [comment]
Oh that's strange. May be for now we can ignore `linux_aarch64`?

**Comment by etjones** [comment]
That was my first thought. So I didn't build against aarch64 and tried again. And then the package submission failed with `linux_i686`. I can keep cutting out the offending platforms, but I suspect there's a small fix that would make everything work. If you're OK waiting, I'll hold off a couple days in the hopes I get a response on the issue I filed.

**Comment by tyt2y3** [comment]
Sure, no problem

**Pull request closed without merging**
