### PR TITLE
Alpha channel handling in CLI

### PR DESCRIPTION
**Pull request by zachwolfe**
This depends on [my PR on visualcortex](https://github.com/visioncortex/visioncortex/pull/6). My approach is first to find a solid color that does not appear anywhere in the input image. Then, I replace all perfectly-transparent pixels with that solid color. Then, I pass the appropriate `KeyingAction` value to effectively ignore all keyed pixels.

### CODE REVIEW

**Comment by tyt2y3** [comment]
Thank you for the contribution!

1) I prefer `fastrand` somehow
2) regarding Hierarchical::Cutout, why do we want to keep the clusters in the first stage (instead of just discarding them)?
3) I think we want to have some checking before applying the keying logic. A good heuristic is that we access the boundary pixels of the image, and only activate this mode if we found enough rgba(0,0,0,0). because it seems that this keying process takes non-zero cost

Great work all-in-all! You are a talent

**Comment by tyt2y3** [comment]
Btw, in order for the CI to build, we can add `git =` temporarily in Cargo, which I will remove after merge.

**Comment by tyt2y3** [comment]
Oh and I suggest that we use 3 additional special key colors #FF0, #0FF, #F0F

**Comment by tyt2y3** [comment]
Actually, I used to do a dirty trick to replace all (255,255,0) with (255, 254, 0) and call it a day

**Comment by zachwolfe** [comment]
1. Sure, I can use `fastrand`. I’ll also add the git url to the dependency and the additional special key colours.
2. I did that because if you discard them in the first stage, the second phase won’t know to discard them because they aren’t the key color anymore.
3. Hmm, yeah that seems reasonable enough. Could you elaborate a bit on what you mean by “boundary pixels”? I’m assuming something like iterating over the top and bottom rows and/or left and right columns?
4. Thanks!

**Comment by zachwolfe** [comment]
> Oh and I suggest that we add 3 additional special key colors #FF0, #0FF, #F0F
> I would say 300 random colors is a little too much, and I afraid it will get slow for large images.
> Probably trying 6 additional times will be all it takes

Yeah, 300 is probably a bit excessive haha.

**Comment by tyt2y3** [comment]
>  iterating over the top and bottom rows and/or left and right columns

Yes. basically just 'too lazy to walk all pixels'

**Comment by zachwolfe** [comment]
Ok, I think I've addressed everything above. Let me know if the heuristic is along the lines of what you were thinking.

**Comment by tyt2y3** [comment]
Cool I am testing it

**Comment by tyt2y3** [comment]
Works like a charm

**Comment by tyt2y3** [comment]
Sadly I found one pathological case. Consider this https://raw.githubusercontent.com/SeaQL/sea-orm/master/docs/SeaQL%20logo%20dual.png image, turning on 'transparency mode' would cause the words missing. 

If I turn off the transparency handling, it would work. I think somewhere is discarding the 'root cluster' in stacked mode. Strangely, it works in 'cutout' mode. So I think this is fixable.

**Comment by zachwolfe** [comment]
Oh, thanks for bringing that to my attention. I’ll investigate soon.

**Comment by zachwolfe** [comment]
It turns out that because the letters' clusters have no neighbours in transparent mode, their clusters will be discarded [here in visioncortex](https://github.com/visioncortex/visioncortex/blob/master/src/color_clusters/builder.rs#L446). If I get rid of that inner if statement (always adding the cluster if there are no neighbours), the letters show up as expected. Since you have a better understanding of the algorithms used than I do, do you think that approach is good enough, or should I explicitly check for transparent neighbours?

**Comment by zachwolfe** [comment]
Thanks for your input. I originally had a more complicated solution where I would keep track of all pixels that were discarded, and then consult that set later. But after you gave me the idea to try checking the key color, I found that that doesn't quite work, but checking the keying action does in both stacked and cutout modes! With no check (or checking the key color), I got some really bizarre results for the SeaQL image in cutout mode, so it does seem necessary.

**Comment by tyt2y3** [comment]
Can you share one of those bizarre results?

**Comment by tyt2y3** [comment]
Actually I think we should step backwards. Maybe those pixels shouldn't be 'ignored'. I think it makes more sense to keep them all in one special cluster, and only remove that in the end, right before vectorisation.

**Comment by tyt2y3** [comment]
Just to be clear, is the results above based on https://github.com/visioncortex/visioncortex/pull/7 or not?

**Comment by zachwolfe** [comment]
Nope, they're based on https://github.com/visioncortex/visioncortex/pull/6, just with
```
match keying_action {
    KeyingAction::Keep => self.get_cluster_mut(ZERO).add(i, &c, x, y),
    KeyingAction::Discard => {},
}
```
reverted to
```
self.get_cluster_mut(ZERO).add(i, &c, x, y);
```

**Comment by zachwolfe** [comment]
> Is there a working version I can try? I am keen to test again

Yes (mostly). This PR + https://github.com/visioncortex/visioncortex/pull/7 works in both modes on the SeaQL logo. However I noticed later that [this image](https://user-images.githubusercontent.com/11866496/187427336-2e2ede8b-d9df-4a83-a4de-7461c0afd33a.png) works in stacked mode, but in cutout mode it currently has some unintended gaps in between clusters:

image

**Comment by tyt2y3** [comment]
Oh great! If everything goes well I'll make a release soon.

I don't think that is a bug relevant to clustering. It's essentially a phenomenon in vectorization. If you tune the curve fitting parameters, the gap might be less visible.

**Comment by zachwolfe** [comment]
Awesome! And that's good to know; I thought I must have been missing something important.

One last thing that's been bugging me: I currently only check the top and bottom rows of the input for transparent pixels, as you know. That means if the outsides are opaque but there's a transparent middle, it will not be detected by my heuristic. Would you mind if I add a check for a small number of inner pixels?

**Comment by tyt2y3** [comment]
Lovely

**Pull request merged**
